name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: Unit Tests
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        node-version: [14, 16]
    runs-on: ${{ matrix.os }}
    env:
      PYTHON: ${{ matrix.python-version }}
      NODE: ${{ matrix.node-version }}
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout the repo
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci

      # run:  pip install poetry tox codecov tox-gh-actions
    - name: Run tests with Python ${{ matrix.python-version }}, Node ${{ matrix.node-version }} on ${{ matrix.os }}
      run: npm t
      
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout the repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run eslint
      run: npm run lint